language: python
cache: pip
dist: bionic
sudo: false

matrix:
    include:
        - python: '3.6'
        - python: '3.7'
        - python: '3.8'
        - python: '3.9'

install:
    - pip install -r requirements.txt --use-deprecated=legacy-resolver
    - pip install -r dev_requirements.txt --use-deprecated=legacy-resolver
    - pip install python-coveralls --use-deprecated=legacy-resolver

script:
    - make lint && make ci

after_success:
    - make coverage
